[project]
name = "FractalViewer"
version = "0.1.0"
description = "Fractal viewer in Python using compute shaders and the Arcade and Pyglet modules."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
 "arcade==3.2.0",
 "pypresence>=4.3.0",
]
